eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: demo1
  datasource:
    username: root
    password: youmi1989
    url: jdbc:mysql://10.0.1.55:3306/youmi
    driver-class-name: com.mysql.jdbc.Driver
  #redis

  #redis配置开始
  # Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: 10.0.1.55
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password:
    pool:
      maxTotal: 10
      maxWaitMillis: 3000
  # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 1024
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
  # 连接池中的最大空闲连接
        max-idle: 200
  # 连接池中的最小空闲连接
        min-idle: 0
        maxTotal: 10
        maxWaitMillis: 3000
  # 连接超时时间（毫秒）
    timeout: 10000
  #redis配置结束
    block-when-exhausted: true


server:
  port: 8084
feign:
  hystrix:
    enabled: true

##mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.youmi.demo.entity.User

