eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gatewaydemo
  cloud:
    gateway:
       discovery:
         locator:
           enabled: true
           lowerCaseServiceId: true
       routes:
         - id: employee-service
           uri: lb://demo
           predicates:
             - Path=/demo/**
           filters:
             - RewritePath=/demo/(?<path>.*), /$\{path}
             - name: Hystrix
               args:
                 name: fallbackcmd
                 fallbackUri: forward:/timeout

server:
  port: 8989











