eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: rab
  rabbitmq:
    host: 10.0.1.55
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
server:
  port: 8189
