eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: rabrev
  rabbitmq:
    host: 10.0.1.55
    port: 5672
    username: guest
    password: guest
server:
  port: 8199
