eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul
server:
  port: 8085
zuul:
  routes:
    youmi:
      path: /youmi/**
      serviceId: demo1


